prometheus:
  enabled: yes
  port: 8000
hap:
  port: 51826
  persist_file: accessory.state
  bridge:
    display_name: Bridge
    bme680:
      enabled: yes
      address: 118 # Primary I2C Address
      name: "Climate Sensor"
    pms5003:
      enabled: yes
      device: "/dev/ttyUSB0"
      baudrate: 9600
      pin_enable: "GPIO22"
      pin_reset: "GPIO27"