{
 "title": "Home",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PM1.0 ug/m3 (ultrafine particles)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ug/m3" } },
   "targets": [
    {
     "expr": "pms5003_pm_ug_per_m3_1{instance=\"localhost:8000\"}",
     "legendFormat": "Measurement"
    }
   ]
  },
  {
   "title": "PM2.5 ug/m3 (combustion particles, organic compounds, metals).",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ug/m3" } },
   "targets": [
    {
     "expr": "pms5003_pm_ug_per_m3_2{instance=\"localhost:8000\"}",
     "legendFormat": "Measurement"
    }
   ]
  },
  {
   "title": "PM10 ug/m3  (dust, pollen, mould spores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ug/m3" } },
   "targets": [
    {
     "expr": "pms5003_pm_ug_per_m3_10{instance=\"localhost:8000\"}",
     "legendFormat": "Measurement"
    }
   ]
  },
  { "title": "Climate Sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature (C)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bme680_temperature_celsius{}" }
   ]
  },
  {
   "title": "Humidity(%rH)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bme680_humidity_rh" }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "bme680_temperature_celsius{}", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "bme680_humidity_rh{}", "legendFormat": "Relative Humidity" }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "bme680_pressure_hpa{}", "legendFormat": "Pressure" }
   ]
  }
 ]
}